### ISSUE TITLE
"pip install" is unavailable

### ISSUE THREAD

**Issue by wuzhy1ng** [aanastasiou/pymotifcounter#1]
Puzzling, I found that using pip install pymotifcounter is unavailable:

```shell
$ pip install pymotifcounter
ERROR: Could not find a version that satisfies the requirement pymotifcounter (from versions: none)
ERROR: No matching distribution found for pymotifcounter
```

**Comment by aanastasiou** [comment]
@wuzhy1ng Indeed. I wanted to include some of the source code I modified but first contact the original authors before I upload it to pypi but then got distracted by work.

You can still `pip install git+https://github.com/aanastasiou/pymotifcounter.git` right into your virtual environment. Let me know how you are getting on or if you need any further help with this module.

All the best

**Comment by aanastasiou** [comment]
@wuzhy1ng You might want to give it another go :) (I would appreciate it if you could let me know of any problems)
